apiVersion: v1
kind: Service
metadata:
  name: restaurant-service1
spec:
  type: NodePort
  selector:
    app: restaurant1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
