apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant1
  template:
    metadata:
      labels:
        app: restaurant1
    spec:
      containers:
      - name: restaurant1
        image: kavyav549/restaurant-site:latest
         imagePullPolicy: Always
        ports:
        - containerPort: 80
