apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant1
  template:
    metadata:
      labels:
        app: restaurant1
    spec:
      containers:
      - name: restaurant-container
        image: kavyav549/restaurant-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service1
spec:
  type: NodePort
  selector:
    app: restaurant1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
